# -*- coding: utf-8 -*-
"""Analyticky blok pod korespondenciou — kde Komisia pochybila. 9 jazykov."""

TITLE = {
"en":"Where the Commission erred",
"sk":"Kde Komisia pochybila",
"de":"Worin die Kommission gefehlt hat",
"hr":"U čemu je Komisija pogriješila",
"pl":"W czym Komisja uchybiła",
"es":"En qué erró la Comisión",
"it":"In che cosa la Commissione ha errato",
"fr":"En quoi la Commission a failli",
"sv":"Var kommissionen har brustit",
}

ANALYSIS = {}

ANALYSIS["en"] = """
<p class="lead">This is not about finding a loophole. The file itself contains several substantive failings which the settled case-law of the Court of Justice recognises as grounds for annulment. They are set out below, strongest first.</p>
<h4>1. The application was lodged in time — and the institution contradicts itself on the same day</h4>
<p>Article 7(2) of Regulation (EC) No 1049/2001 ties the fifteen-day period to receipt of the institution's reply, not to the date on which the reply was drafted. The negative reply of the Directorate-General for Competition is dated 7 January 2026; the period therefore ran until the end of January. That is confirmed by the Commission's own letter of 20 January 2026, in which it stated in writing that the period had not then expired.</p>
<p>I drafted and lodged the confirmatory application on 26 January 2026 — the last day of the period — through the AskTheEU platform. Access Info Europe has confirmed in writing the receipt of the message, time-stamped on that date, and is prepared to attest to it. A technical interface error meant that the platform did not immediately forward the submission to the institution; I therefore sent it directly on 30 January.</p>
<p>What matters is what happened on 3 February 2026. On that day unit COMP C-5 acknowledged receipt of the confirmatory application and forwarded it to the Secretariat-General — a formal procedural act placing the submission within the regime of Regulation 1049/2001. On the very same day the Secretariat-General rejected that same submission as lodged out of time. One part of the institution thus processes the application as admissible while another declares it inadmissible on the same day.</p>
<p>This is not a contradiction separated by weeks, which the passage of time might explain. These are two mutually irreconcilable acts of the same institution on a single day. The rejection moreover does not address the documented submission of 26 January or the written confirmation from Access Info Europe — it tacitly proceeds from the date of 30 January as if the earlier filing did not exist.</p>
<h4>2. Procedural acceptance that cannot be withdrawn</h4>
<p>On 3 February unit COMP C-5 acknowledged receipt of the confirmatory application and forwarded it to the Secretariat-General, thereby placing it within the regime of Regulation 1049/2001. Only afterwards came the rejection for lateness. Retroactively denying an application already accepted and processed is difficult to reconcile with the principle of good administration (Article 41 of the Charter) and with the protection of legitimate expectations.</p>
<h4>3. A rebuttable presumption that cannot be rebutted</h4>
<p>The refusal relies on the general presumption of confidentiality applied in merger files (Odile Jacob, C-404/10 P; Agrofert, C-477/10 P). Under that case-law the presumption is <strong>rebuttable</strong>. Yet I am reproached for not having rebutted it while being denied even an inventory of the file. A presumption cannot be rebutted in respect of documents whose list is withheld. That reasoning is internally contradictory.</p>
<h4>4. The presumption does not cover everything</h4>
<p>The general presumption concerns documents exchanged with the notifying parties. It does not extend automatically to DG Competition's own internal market analyses, nor to the unredacted text of the Commission's decision. Those are acts of the institution, not submissions of the parties, and required an individual assessment which the decision does not contain.</p>
<h4>5. Partial access was not assessed</h4>
<p>Article 4(6) of the Regulation requires that, where only parts of a document are covered by an exception, the remaining parts be released. The decision does not show that this was considered at all.</p>
<h4>6. Overriding public interest and the GDPR gap</h4>
<p>Where commercial interests are invoked under Article 4(2), access must still be granted if there is an overriding public interest in disclosure. In recitals 138 to 142 of decision M.10815 the Commission itself states that it did not assess the parties' compliance with the GDPR. A gap acknowledged by the institution cannot be covered by blanket confidentiality.</p>
<p class="closing"><strong>The point is not a technicality</strong> but the combination of contradictory conduct (points 1 and 2) with insufficient individual reasoning (points 3 to 5). By the letter of 20 July 2026 I reserved a complaint to the European Ombudsman and an action under Article 263 TFEU. Article 8(3) of the Regulation further provides that a failure to reply within the prescribed time limit is to be treated as a negative reply, opening the same avenues of redress.</p>"""

ANALYSIS["sk"] = """
<p class="lead">Nejde o hľadanie skuliny. Samotný spis obsahuje niekoľko vecných pochybení, ktoré ustálená judikatúra Súdneho dvora uznáva ako dôvody na zrušenie rozhodnutia. Uvádzam ich zoradené od najsilnejšieho.</p>
<h4>1. Podanie bolo včasné — a inštitúcia si v ten istý deň odporuje</h4>
<p>Článok 7 ods. 2 nariadenia (ES) č. 1049/2001 viaže pätnásťdňovú lehotu na doručenie odpovede inštitúcie, nie na dátum, kedy bola odpoveď napísaná. Zamietavá odpoveď Generálneho riaditeľstva pre hospodársku súťaž je zo 7. januára 2026; lehota teda plynula do konca januára. Tomu zodpovedá aj list Komisie z 20. januára 2026, v ktorom mi sama písomne potvrdila, že lehota v tom čase ešte neuplynula.</p>
<p>Potvrdzovaciu žiadosť som vypracoval a podal 26. januára 2026, teda v posledný deň lehoty, prostredníctvom platformy AskTheEU. Organizácia Access Info Europe písomne potvrdila prijatie správy s časovou pečiatkou z toho dňa a je pripravená to dosvedčiť. Technická chyba rozhrania spôsobila, že platforma podanie okamžite nepostúpila inštitúcii; 30. januára som ho preto zaslal priamo.</p>
<p>Rozhodujúce je, čo sa stalo 3. februára 2026. Útvar COMP C-5 v ten deň potvrdil prijatie potvrdzovacej žiadosti a postúpil ju Generálnemu sekretariátu — formálny procesný úkon, ktorým podanie zaradil do režimu nariadenia 1049/2001. V ten istý deň Generálny sekretariát to isté podanie zamietol ako oneskorené. Jedna zložka inštitúcie teda podanie spracúva ako prípustné, kým druhá ho v ten istý deň vyhlasuje za neprípustné.</p>
<p>Nejde o rozpor s odstupom týždňov, ktorý by sa dal vysvetliť plynutím času. Ide o dva navzájom nezlučiteľné úkony toho istého orgánu v jeden deň. Zamietnutie navyše nijako nereaguje na doložené podanie z 26. januára ani na písomné potvrdenie Access Info Europe — mlčky vychádza z dátumu 30. januára, akoby skoršie podanie neexistovalo.</p>
<h4>2. Procesné prijatie, ktoré nemožno vziať späť</h4>
<p>Dňa 3. februára útvar COMP C-5 potvrdil prijatie potvrdzovacej žiadosti a postúpil ju Generálnemu sekretariátu, čím ju zaradil do režimu nariadenia 1049/2001. Až potom prišlo zamietnutie pre oneskorenosť. Spätné popretie podania, ktoré už bolo prijaté a spracúvané, sa ťažko zlučuje so zásadou dobrej správy vecí verejných (článok 41 Charty) a s ochranou legitímnych očakávaní.</p>
<h4>3. Vyvrátiteľná domnienka, ktorú nemožno vyvrátiť</h4>
<p>Zamietnutie sa opiera o všeobecnú domnienku dôvernosti uplatňovanú v spisoch o fúziách (Odile Jacob, C-404/10 P; Agrofert, C-477/10 P). Podľa tejto judikatúry je domnienka <strong>vyvrátiteľná</strong>. Vyčíta sa mi však, že som ju nevyvrátil, pričom mi odmietajú sprístupniť čo i len inventár spisu. Domnienku nemožno vyvrátiť vo vzťahu k dokumentom, ktorých zoznam sa zadržiava. Také odôvodnenie je vnútorne rozporné.</p>
<h4>4. Domnienka nepokrýva všetko</h4>
<p>Všeobecná domnienka sa týka dokumentov vymenených s oznamujúcimi stranami. Nevzťahuje sa automaticky na vlastné interné trhové analýzy GR pre hospodársku súťaž ani na nezačiernené znenie rozhodnutia Komisie. To sú akty inštitúcie, nie podania strán, a vyžadovali si individuálne posúdenie, ktoré rozhodnutie neobsahuje.</p>
<h4>5. Čiastočný prístup nebol posúdený</h4>
<p>Článok 4 ods. 6 nariadenia prikazuje, že ak sa výnimka vzťahuje len na časti dokumentu, zvyšné časti sa musia sprístupniť. Z rozhodnutia nevyplýva, že by to Komisia vôbec zvažovala.</p>
<h4>6. Prevažujúci verejný záujem a medzera pri GDPR</h4>
<p>Ak sa uplatňujú obchodné záujmy podľa článku 4 ods. 2, prístup sa musí priznať napriek tomu, ak existuje prevažujúci verejný záujem na sprístupnení. V bodoch 138 až 142 rozhodnutia M.10815 Komisia sama uvádza, že súlad strán s GDPR neposudzovala. Medzeru, ktorú inštitúcia priznáva, nemožno kryť plošným utajením.</p>
<p class="closing"><strong>Podstatou nie je formalita</strong>, ale kombinácia rozporného konania (body 1 a 2) s nedostatočným individuálnym odôvodnením (body 3 až 5). Listom z 20. júla 2026 som si vyhradil sťažnosť európskemu ombudsmanovi a žalobu podľa článku 263 ZFEÚ. Článok 8 ods. 3 nariadenia navyše ustanovuje, že nedodržanie lehoty na odpoveď sa považuje za zápornú odpoveď, čo otvára tie isté prostriedky nápravy.</p>"""

ANALYSIS["de"] = """
<p class="lead">Es geht nicht darum, eine Lücke zu suchen. Die Akte selbst enthält mehrere sachliche Fehler, die die ständige Rechtsprechung des Gerichtshofs als Aufhebungsgründe anerkennt. Sie sind nachstehend aufgeführt, beginnend mit dem stärksten.</p>
<h4>1. Die Eingabe war fristgerecht — und das Organ widerspricht sich am selben Tag</h4>
<p>Artikel 7 Absatz 2 der Verordnung (EG) Nr. 1049/2001 knüpft die Frist von fünfzehn Tagen an den Eingang der Antwort des Organs, nicht an das Datum, an dem die Antwort verfasst wurde. Die ablehnende Antwort der Generaldirektion Wettbewerb datiert vom 7. Januar 2026; die Frist lief somit bis Ende Januar. Dem entspricht auch das Schreiben der Kommission vom 20. Januar 2026, in dem sie mir schriftlich bestätigte, dass die Frist zu diesem Zeitpunkt noch nicht abgelaufen war.</p>
<p>Den Zweitantrag habe ich am 26. Januar 2026 — am letzten Tag der Frist — über die Plattform AskTheEU verfasst und eingereicht. Access Info Europe hat den Eingang der Nachricht mit Zeitstempel dieses Tages schriftlich bestätigt und ist bereit, dies zu bezeugen. Ein technischer Fehler der Schnittstelle führte dazu, dass die Plattform die Eingabe nicht sogleich an das Organ weiterleitete; am 30. Januar habe ich sie daher unmittelbar übersandt.</p>
<p>Entscheidend ist, was am 3. Februar 2026 geschah. An diesem Tag bestätigte das Referat COMP C-5 den Eingang des Zweitantrags und leitete ihn an das Generalsekretariat weiter — ein förmlicher Verfahrensakt, der die Eingabe dem Regime der Verordnung 1049/2001 zuordnete. Am selben Tag wies das Generalsekretariat dieselbe Eingabe als verspätet zurück. Ein Teil des Organs behandelt den Antrag somit als zulässig, während ein anderer ihn am selben Tag für unzulässig erklärt.</p>
<p>Es handelt sich nicht um einen durch Wochen getrennten Widerspruch, den der Zeitablauf erklären könnte. Es sind zwei miteinander unvereinbare Handlungen desselben Organs an einem einzigen Tag. Die Zurückweisung geht überdies weder auf die belegte Eingabe vom 26. Januar noch auf die schriftliche Bestätigung von Access Info Europe ein — sie legt stillschweigend das Datum des 30. Januar zugrunde, als hätte die frühere Einreichung nicht stattgefunden.</p>
<h4>2. Verfahrensrechtliche Annahme, die nicht zurückgenommen werden kann</h4>
<p>Am 3. Februar bestätigte das Referat COMP C-5 den Eingang des Zweitantrags und leitete ihn an das Generalsekretariat weiter und ordnete ihn damit dem Regime der Verordnung 1049/2001 zu. Erst danach kam die Zurückweisung wegen Verspätung. Die rückwirkende Verneinung einer bereits angenommenen und bearbeiteten Eingabe lässt sich mit dem Grundsatz der guten Verwaltung (Artikel 41 der Charta) und dem Vertrauensschutz kaum vereinbaren.</p>
<h4>3. Eine widerlegbare Vermutung, die nicht widerlegt werden kann</h4>
<p>Die Ablehnung stützt sich auf die allgemeine Vertraulichkeitsvermutung in Fusionsakten (Odile Jacob, C-404/10 P; Agrofert, C-477/10 P). Nach dieser Rechtsprechung ist die Vermutung <strong>widerlegbar</strong>. Mir wird jedoch vorgehalten, ich hätte sie nicht widerlegt, während mir nicht einmal ein Aktenverzeichnis zugänglich gemacht wird. Eine Vermutung kann nicht in Bezug auf Dokumente widerlegt werden, deren Liste zurückgehalten wird. Diese Begründung ist in sich widersprüchlich.</p>
<h4>4. Die Vermutung erfasst nicht alles</h4>
<p>Die allgemeine Vermutung betrifft die mit den anmeldenden Parteien ausgetauschten Unterlagen. Sie erstreckt sich nicht automatisch auf die eigenen internen Marktanalysen der GD Wettbewerb oder auf die ungeschwärzte Fassung des Kommissionsbeschlusses. Das sind Akte des Organs, keine Eingaben der Parteien, und sie erforderten eine individuelle Prüfung, die der Beschluss nicht enthält.</p>
<h4>5. Der Teilzugang wurde nicht geprüft</h4>
<p>Artikel 4 Absatz 6 der Verordnung verlangt, dass bei nur teilweise erfassten Dokumenten die übrigen Teile freigegeben werden. Der Beschluss lässt nicht erkennen, dass dies überhaupt erwogen wurde.</p>
<h4>6. Überwiegendes öffentliches Interesse und die DSGVO-Lücke</h4>
<p>Werden geschäftliche Interessen nach Artikel 4 Absatz 2 geltend gemacht, ist der Zugang gleichwohl zu gewähren, wenn ein überwiegendes öffentliches Interesse an der Verbreitung besteht. In den Randnummern 138 bis 142 des Beschlusses M.10815 führt die Kommission selbst aus, dass sie die Einhaltung der DSGVO durch die Beteiligten nicht geprüft hat. Eine vom Organ eingeräumte Lücke lässt sich nicht durch pauschale Geheimhaltung decken.</p>
<p class="closing"><strong>Der Kern ist keine Formalie</strong>, sondern die Verbindung widersprüchlichen Handelns (Punkte 1 und 2) mit unzureichender Einzelbegründung (Punkte 3 bis 5). Mit Schreiben vom 20. Juli 2026 habe ich mir eine Beschwerde beim Europäischen Bürgerbeauftragten und eine Klage nach Artikel 263 AEUV vorbehalten. Artikel 8 Absatz 3 der Verordnung bestimmt zudem, dass das Ausbleiben einer fristgemäßen Antwort als ablehnende Antwort gilt, was dieselben Rechtsbehelfe eröffnet.</p>"""

ANALYSIS["hr"] = """
<p class="lead">Ne radi se o traženju rupe u propisu. Sam spis sadržava nekoliko sadržajnih pogrešaka koje ustaljena sudska praksa Suda priznaje kao razloge za poništenje. Navedene su redom, od najjače.</p>
<h4>1. Podnesak je bio pravodoban — a institucija si isti dan proturječi</h4>
<p>Članak 7. stavak 2. Uredbe (EZ) br. 1049/2001 veže rok od petnaest dana uz primitak odgovora institucije, a ne uz datum kad je odgovor sastavljen. Odbijajući odgovor Glavne uprave za tržišno natjecanje datiran je 7. siječnja 2026.; rok je stoga tekao do kraja siječnja. Tome odgovara i dopis Komisije od 20. siječnja 2026., u kojem mi je sama pisano potvrdila da rok tada još nije istekao.</p>
<p>Ponovni sam zahtjev sastavio i podnio 26. siječnja 2026. — posljednjeg dana roka — putem platforme AskTheEU. Access Info Europe pisano je potvrdio primitak poruke s vremenskim žigom toga dana i spreman je to posvjedočiti. Tehnička pogreška sučelja dovela je do toga da platforma podnesak nije odmah proslijedila instituciji; stoga sam ga 30. siječnja poslao izravno.</p>
<p>Odlučujuće je što se dogodilo 3. veljače 2026. Toga je dana odjel COMP C-5 potvrdio primitak ponovnog zahtjeva i proslijedio ga Glavnom tajništvu — formalni postupovni akt kojim je podnesak uvrstio u režim Uredbe 1049/2001. Istoga je dana Glavno tajništvo taj isti podnesak odbacilo kao nepravodoban. Jedan dio institucije dakle zahtjev obrađuje kao dopušten, dok ga drugi istoga dana proglašava nedopuštenim.</p>
<p>Nije riječ o proturječju razdvojenom tjednima, koje bi se moglo objasniti protekom vremena. Riječ je o dva međusobno nespojiva akta iste institucije u jednom danu. Odbacivanje se usto uopće ne osvrće na dokumentirani podnesak od 26. siječnja ni na pisanu potvrdu Access Info Europe — prešutno polazi od datuma 30. siječnja, kao da ranije podnošenje nije postojalo.</p>
<h4>2. Postupovni primitak koji se ne može povući</h4>
<p>Dana 3. veljače odjel COMP C-5 potvrdio je primitak ponovnog zahtjeva i proslijedio ga Glavnom tajništvu, čime ga je uvrstio u režim Uredbe 1049/2001. Tek je nakon toga uslijedilo odbacivanje zbog zakašnjenja. Retroaktivno nijekanje podneska koji je već zaprimljen i obrađivan teško je uskladiti s načelom dobre uprave (članak 41. Povelje) i sa zaštitom legitimnih očekivanja.</p>
<h4>3. Oboriva presumpcija koja se ne može oboriti</h4>
<p>Odbijanje se oslanja na opću presumpciju povjerljivosti u spisima o koncentracijama (Odile Jacob, C-404/10 P; Agrofert, C-477/10 P). Prema toj je sudskoj praksi presumpcija <strong>oboriva</strong>. Meni se pak prigovara da je nisam oborio, a istodobno mi se uskraćuje i sam popis spisa. Presumpcija se ne može oboriti u odnosu na dokumente čiji se popis zadržava. Takvo je obrazloženje unutarnje proturječno.</p>
<h4>4. Presumpcija ne pokriva sve</h4>
<p>Opća se presumpcija odnosi na dokumente razmijenjene sa strankama koje su podnijele prijavu. Ne proteže se automatski na vlastite interne tržišne analize Glavne uprave za tržišno natjecanje ni na necenzuriranu verziju odluke Komisije. To su akti institucije, a ne podnesci stranaka, i zahtijevali su pojedinačnu ocjenu koju odluka ne sadržava.</p>
<h4>5. Djelomičan pristup nije ocijenjen</h4>
<p>Članak 4. stavak 6. Uredbe nalaže da se, kad su iznimkom obuhvaćeni samo dijelovi dokumenta, preostali dijelovi objave. Iz odluke nije vidljivo da je to uopće razmotreno.</p>
<h4>6. Prevladavajući javni interes i praznina u pogledu GDPR-a</h4>
<p>Kad se pozivaju komercijalni interesi iz članka 4. stavka 2., pristup se ipak mora odobriti postoji li prevladavajući javni interes za otkrivanjem. U točkama 138. do 142. odluke M.10815 Komisija sama navodi da nije ocjenjivala usklađenost stranaka s GDPR-om. Praznina koju institucija priznaje ne može se pokriti paušalnom tajnošću.</p>
<p class="closing"><strong>Bit nije formalnost</strong>, nego spoj proturječnog postupanja (točke 1. i 2.) s nedostatnim pojedinačnim obrazloženjem (točke 3. do 5.). Dopisom od 20. srpnja 2026. pridržao sam pravo na pritužbu Europskom ombudsmanu i na tužbu na temelju članka 263. UFEU-a. Članak 8. stavak 3. Uredbe usto propisuje da se izostanak pravodobnog odgovora smatra negativnim odgovorom, čime se otvaraju isti pravni lijekovi.</p>"""

ANALYSIS["pl"] = """
<p class="lead">Nie chodzi o szukanie luki. Same akta zawierają kilka merytorycznych uchybień, które utrwalone orzecznictwo Trybunału uznaje za podstawy stwierdzenia nieważności. Podaję je od najmocniejszego.</p>
<h4>1. Wniosek złożono w terminie — a instytucja przeczy sobie tego samego dnia</h4>
<p>Artykuł 7 ust. 2 rozporządzenia (WE) nr 1049/2001 wiąże piętnastodniowy termin z otrzymaniem odpowiedzi instytucji, a nie z datą jej sporządzenia. Odmowna odpowiedź Dyrekcji Generalnej ds. Konkurencji nosi datę 7 stycznia 2026 r.; termin biegł zatem do końca stycznia. Odpowiada temu również pismo Komisji z 20 stycznia 2026 r., w którym sama potwierdziła mi na piśmie, że termin wówczas jeszcze nie upłynął.</p>
<p>Wniosek potwierdzający sporządziłem i złożyłem 26 stycznia 2026 r. — w ostatnim dniu terminu — za pośrednictwem platformy AskTheEU. Access Info Europe potwierdziło na piśmie wpływ wiadomości opatrzonej znacznikiem czasu z tego dnia i jest gotowe to poświadczyć. Błąd techniczny interfejsu sprawił, że platforma nie przekazała pisma instytucji od razu; dlatego 30 stycznia wysłałem je bezpośrednio.</p>
<p>Rozstrzygające jest to, co wydarzyło się 3 lutego 2026 r. Tego dnia dział COMP C-5 potwierdził wpływ wniosku potwierdzającego i przekazał go Sekretariatowi Generalnemu — formalna czynność procesowa umieszczająca pismo w reżimie rozporządzenia 1049/2001. Tego samego dnia Sekretariat Generalny odrzucił to samo pismo jako spóźnione. Jedna część instytucji rozpatruje więc wniosek jako dopuszczalny, podczas gdy druga tego samego dnia uznaje go za niedopuszczalny.</p>
<p>Nie jest to sprzeczność rozdzielona tygodniami, którą mógłby tłumaczyć upływ czasu. Są to dwie wzajemnie nie do pogodzenia czynności tej samej instytucji w jednym dniu. Odrzucenie ponadto w żaden sposób nie odnosi się do udokumentowanego pisma z 26 stycznia ani do pisemnego potwierdzenia Access Info Europe — milcząco przyjmuje datę 30 stycznia, jakby wcześniejsze złożenie nie istniało.</p>
<h4>2. Przyjęcie proceduralne, którego nie można cofnąć</h4>
<p>W dniu 3 lutego dział COMP C-5 potwierdził wpływ wniosku potwierdzającego i przekazał go Sekretariatowi Generalnemu, tym samym umieszczając go w reżimie rozporządzenia 1049/2001. Dopiero potem nastąpiło odrzucenie z powodu spóźnienia. Wsteczne zanegowanie pisma już przyjętego i rozpatrywanego trudno pogodzić z zasadą dobrej administracji (art. 41 Karty) i z ochroną uzasadnionych oczekiwań.</p>
<h4>3. Domniemanie wzruszalne, którego nie można obalić</h4>
<p>Odmowa opiera się na ogólnym domniemaniu poufności stosowanym w aktach koncentracji (Odile Jacob, C-404/10 P; Agrofert, C-477/10 P). Zgodnie z tym orzecznictwem domniemanie jest <strong>wzruszalne</strong>. Zarzuca mi się jednak, że go nie obaliłem, odmawiając mi jednocześnie choćby spisu akt. Domniemania nie można obalić w odniesieniu do dokumentów, których wykaz jest zatrzymywany. Takie uzasadnienie jest wewnętrznie sprzeczne.</p>
<h4>4. Domniemanie nie obejmuje wszystkiego</h4>
<p>Ogólne domniemanie dotyczy dokumentów wymienionych ze stronami zgłaszającymi. Nie rozciąga się automatycznie na własne wewnętrzne analizy rynkowe DG ds. Konkurencji ani na nieocenzurowaną wersję decyzji Komisji. Są to akty instytucji, a nie pisma stron, i wymagały indywidualnej oceny, której decyzja nie zawiera.</p>
<h4>5. Dostęp częściowy nie został oceniony</h4>
<p>Artykuł 4 ust. 6 rozporządzenia nakazuje, aby w przypadku gdy wyjątek obejmuje jedynie części dokumentu, pozostałe części zostały udostępnione. Z decyzji nie wynika, by w ogóle to rozważono.</p>
<h4>6. Nadrzędny interes publiczny i luka dotycząca RODO</h4>
<p>Gdy powołuje się interesy handlowe z art. 4 ust. 2, dostępu należy mimo to udzielić, jeżeli istnieje nadrzędny interes publiczny w ujawnieniu. W motywach 138–142 decyzji M.10815 Komisja sama stwierdza, że nie badała zgodności stron z RODO. Luki przyznanej przez instytucję nie można przykryć blankietową poufnością.</p>
<p class="closing"><strong>Istotą nie jest formalizm</strong>, lecz połączenie sprzecznego postępowania (pkt 1 i 2) z niedostatecznym uzasadnieniem indywidualnym (pkt 3–5). Pismem z 20 lipca 2026 r. zastrzegłem skargę do Europejskiego Rzecznika Praw Obywatelskich oraz skargę na podstawie art. 263 TFUE. Artykuł 8 ust. 3 rozporządzenia stanowi ponadto, że brak odpowiedzi w wyznaczonym terminie uważa się za odpowiedź odmowną, co otwiera te same środki zaskarżenia.</p>"""

ANALYSIS["es"] = """
<p class="lead">No se trata de buscar un resquicio. El propio expediente contiene varios errores sustantivos que la jurisprudencia reiterada del Tribunal de Justicia reconoce como motivos de anulación. Se exponen a continuación, empezando por el más sólido.</p>
<h4>1. La solicitud se presentó en plazo — y la institución se contradice el mismo día</h4>
<p>El artículo 7, apartado 2, del Reglamento (CE) n.º 1049/2001 vincula el plazo de quince días a la recepción de la respuesta de la institución, no a la fecha en que la respuesta fue redactada. La respuesta denegatoria de la Dirección General de Competencia lleva fecha de 7 de enero de 2026; el plazo corría, por tanto, hasta finales de enero. A ello responde también el escrito de la Comisión de 20 de enero de 2026, en el que ella misma me confirmó por escrito que el plazo no había expirado entonces.</p>
<p>Redacté y presenté la solicitud confirmatoria el 26 de enero de 2026 — el último día del plazo — a través de la plataforma AskTheEU. Access Info Europe ha confirmado por escrito la recepción del mensaje, con sello de tiempo de esa fecha, y está dispuesta a atestiguarlo. Un error técnico de la interfaz impidió que la plataforma remitiera de inmediato el escrito a la institución; por ello lo envié directamente el 30 de enero.</p>
<p>Lo decisivo es lo ocurrido el 3 de febrero de 2026. Ese día la unidad COMP C-5 acusó recibo de la solicitud confirmatoria y la remitió a la Secretaría General — un acto procedimental formal que situó el escrito en el régimen del Reglamento 1049/2001. Ese mismo día la Secretaría General rechazó ese mismo escrito por extemporáneo. Una parte de la institución tramita así la solicitud como admisible mientras otra la declara inadmisible el mismo día.</p>
<p>No se trata de una contradicción separada por semanas, que el transcurso del tiempo pudiera explicar. Son dos actos mutuamente irreconciliables de la misma institución en un solo día. El rechazo, además, no se pronuncia en absoluto sobre el escrito documentado de 26 de enero ni sobre la confirmación escrita de Access Info Europe: parte tácitamente de la fecha de 30 de enero como si la presentación anterior no hubiera existido.</p>
<h4>2. Una aceptación procedimental que no puede retirarse</h4>
<p>El 3 de febrero la unidad COMP C-5 acusó recibo de la solicitud confirmatoria y la remitió a la Secretaría General, situándola así en el régimen del Reglamento 1049/2001. Solo después llegó el rechazo por extemporaneidad. Negar retroactivamente un escrito ya aceptado y tramitado difícilmente se concilia con el principio de buena administración (artículo 41 de la Carta) y con la protección de la confianza legítima.</p>
<h4>3. Una presunción iuris tantum que no puede destruirse</h4>
<p>La denegación se apoya en la presunción general de confidencialidad aplicada en los expedientes de concentraciones (Odile Jacob, C-404/10 P; Agrofert, C-477/10 P). Según esa jurisprudencia la presunción es <strong>iuris tantum</strong>. Sin embargo se me reprocha no haberla destruido mientras se me niega incluso el inventario del expediente. No cabe destruir una presunción respecto de documentos cuya lista se retiene. Ese razonamiento es internamente contradictorio.</p>
<h4>4. La presunción no lo cubre todo</h4>
<p>La presunción general se refiere a los documentos intercambiados con las partes notificantes. No se extiende automáticamente a los análisis de mercado internos de la propia DG Competencia ni a la versión no censurada de la decisión de la Comisión. Son actos de la institución, no escritos de las partes, y exigían una apreciación individual que la decisión no contiene.</p>
<h4>5. No se evaluó el acceso parcial</h4>
<p>El artículo 4, apartado 6, del Reglamento exige que, cuando la excepción solo afecte a partes del documento, se divulguen las restantes. La decisión no muestra que ello se haya considerado siquiera.</p>
<h4>6. Interés público superior y la laguna del RGPD</h4>
<p>Cuando se invocan intereses comerciales conforme al artículo 4, apartado 2, el acceso debe concederse igualmente si existe un interés público superior en la divulgación. En los considerandos 138 a 142 de la decisión M.10815 la Comisión afirma que no evaluó el cumplimiento del RGPD por las partes. Una laguna reconocida por la institución no puede cubrirse con una confidencialidad global.</p>
<p class="closing"><strong>La clave no es un tecnicismo</strong>, sino la combinación de una conducta contradictoria (puntos 1 y 2) con una motivación individual insuficiente (puntos 3 a 5). Mediante el escrito de 20 de julio de 2026 me reservé una reclamación ante el Defensor del Pueblo Europeo y un recurso conforme al artículo 263 TFUE. El artículo 8, apartado 3, del Reglamento dispone además que la falta de respuesta en el plazo señalado se considera respuesta denegatoria, lo que abre las mismas vías de recurso.</p>"""

ANALYSIS["it"] = """
<p class="lead">Non si tratta di cercare una scappatoia. Il fascicolo stesso contiene diversi errori sostanziali che la giurisprudenza costante della Corte riconosce come motivi di annullamento. Sono esposti di seguito, a partire dal più solido.</p>
<h4>1. La domanda è stata presentata nei termini — e l'istituzione si contraddice lo stesso giorno</h4>
<p>L'articolo 7, paragrafo 2, del regolamento (CE) n. 1049/2001 collega il termine di quindici giorni al ricevimento della risposta dell'istituzione, non alla data in cui la risposta è stata redatta. La risposta negativa della Direzione generale della Concorrenza reca la data del 7 gennaio 2026; il termine decorreva quindi fino alla fine di gennaio. A ciò corrisponde anche la lettera della Commissione del 20 gennaio 2026, con cui essa stessa mi ha confermato per iscritto che il termine non era allora ancora scaduto.</p>
<p>Ho redatto e presentato la domanda di conferma il 26 gennaio 2026 — l'ultimo giorno del termine — tramite la piattaforma AskTheEU. Access Info Europe ha confermato per iscritto la ricezione del messaggio, con marca temporale di quella data, ed è pronta ad attestarlo. Un errore tecnico dell'interfaccia ha impedito alla piattaforma di trasmettere immediatamente l'istanza all'istituzione; il 30 gennaio l'ho pertanto inviata direttamente.</p>
<p>Ciò che conta è quanto avvenuto il 3 febbraio 2026. Quel giorno l'unità COMP C-5 ha accusato ricevuta della domanda di conferma e l'ha trasmessa al Segretariato generale — un atto procedurale formale che ha collocato l'istanza nel regime del regolamento 1049/2001. Lo stesso giorno il Segretariato generale ha respinto la medesima istanza perché tardiva. Una parte dell'istituzione tratta dunque la domanda come ricevibile mentre un'altra la dichiara irricevibile nello stesso giorno.</p>
<p>Non si tratta di una contraddizione separata da settimane, che il decorso del tempo potrebbe spiegare. Sono due atti tra loro inconciliabili della stessa istituzione in un solo giorno. Il rigetto, inoltre, non si pronuncia affatto sull'istanza documentata del 26 gennaio né sulla conferma scritta di Access Info Europe: muove tacitamente dalla data del 30 gennaio come se il deposito anteriore non fosse esistito.</p>
<h4>2. Un'accettazione procedurale non revocabile</h4>
<p>Il 3 febbraio l'unità COMP C-5 ha accusato ricevuta della domanda di conferma e l'ha trasmessa al Segretariato generale, collocandola così nel regime del regolamento 1049/2001. Solo in seguito è giunto il rigetto per tardività. Negare retroattivamente un'istanza già ricevuta e trattata è difficilmente conciliabile con il principio di buona amministrazione (articolo 41 della Carta) e con la tutela del legittimo affidamento.</p>
<h4>3. Una presunzione relativa che non può essere superata</h4>
<p>Il diniego si fonda sulla presunzione generale di riservatezza applicata ai fascicoli in materia di concentrazioni (Odile Jacob, C-404/10 P; Agrofert, C-477/10 P). Secondo tale giurisprudenza la presunzione è <strong>relativa</strong>. Mi si rimprovera tuttavia di non averla superata, negandomi al contempo persino l'elenco del fascicolo. Una presunzione non può essere superata riguardo a documenti il cui elenco viene trattenuto. Tale motivazione è intrinsecamente contraddittoria.</p>
<h4>4. La presunzione non copre tutto</h4>
<p>La presunzione generale riguarda i documenti scambiati con le parti notificanti. Non si estende automaticamente alle analisi di mercato interne della stessa DG Concorrenza né alla versione non oscurata della decisione della Commissione. Sono atti dell'istituzione, non istanze delle parti, e richiedevano una valutazione individuale che la decisione non contiene.</p>
<h4>5. L'accesso parziale non è stato valutato</h4>
<p>L'articolo 4, paragrafo 6, del regolamento impone che, quando l'eccezione riguarda solo parti del documento, le parti restanti siano divulgate. Dalla decisione non risulta che ciò sia stato minimamente considerato.</p>
<h4>6. Interesse pubblico prevalente e la lacuna sul GDPR</h4>
<p>Quando si invocano interessi commerciali ai sensi dell'articolo 4, paragrafo 2, l'accesso deve comunque essere concesso se sussiste un interesse pubblico prevalente alla divulgazione. Ai punti da 138 a 142 della decisione M.10815 la Commissione afferma di non aver valutato la conformità delle parti al GDPR. Una lacuna riconosciuta dall'istituzione non può essere coperta da una riservatezza generalizzata.</p>
<p class="closing"><strong>Il nodo non è un tecnicismo</strong>, bensì la combinazione di una condotta contraddittoria (punti 1 e 2) con una motivazione individuale insufficiente (punti da 3 a 5). Con la lettera del 20 luglio 2026 mi sono riservato un reclamo al Mediatore europeo e un ricorso ai sensi dell'articolo 263 TFUE. L'articolo 8, paragrafo 3, del regolamento dispone inoltre che la mancata risposta entro il termine prescritto equivale a una risposta negativa, il che apre gli stessi rimedi.</p>"""

ANALYSIS["fr"] = """
<p class="lead">Il ne s'agit pas de chercher une faille. Le dossier lui-même comporte plusieurs erreurs de fond que la jurisprudence constante de la Cour reconnaît comme des motifs d'annulation. Elles sont exposées ci-dessous, en commençant par la plus solide.</p>
<h4>1. La demande a été déposée dans les délais — et l'institution se contredit le même jour</h4>
<p>L'article 7, paragraphe 2, du règlement (CE) n° 1049/2001 rattache le délai de quinze jours à la réception de la réponse de l'institution, et non à la date à laquelle la réponse a été rédigée. La réponse négative de la direction générale de la concurrence est datée du 7 janvier 2026 ; le délai courait donc jusqu'à la fin janvier. C'est ce que confirme la lettre de la Commission du 20 janvier 2026, par laquelle elle m'a elle-même indiqué par écrit que le délai n'avait alors pas expiré.</p>
<p>J'ai rédigé et déposé la demande confirmative le 26 janvier 2026 — le dernier jour du délai — via la plateforme AskTheEU. Access Info Europe a confirmé par écrit la réception du message, horodaté à cette date, et est prête à en attester. Une erreur technique d'interface a empêché la plateforme de transmettre immédiatement l'écrit à l'institution ; je l'ai donc adressé directement le 30 janvier.</p>
<p>Ce qui est déterminant, c'est ce qui s'est passé le 3 février 2026. Ce jour-là, l'unité COMP C-5 a accusé réception de la demande confirmative et l'a transmise au Secrétariat général — acte procédural formel plaçant l'écrit dans le régime du règlement 1049/2001. Le même jour, le Secrétariat général a rejeté ce même écrit comme tardif. Une partie de l'institution traite ainsi la demande comme recevable tandis qu'une autre la déclare irrecevable le même jour.</p>
<p>Il ne s'agit pas d'une contradiction séparée par des semaines, que l'écoulement du temps pourrait expliquer. Ce sont deux actes inconciliables de la même institution en une seule journée. Le rejet ne se prononce en outre nullement sur l'écrit documenté du 26 janvier ni sur la confirmation écrite d'Access Info Europe : il part tacitement de la date du 30 janvier comme si le dépôt antérieur n'avait pas existé.</p>
<h4>2. Une acceptation procédurale qui ne peut être retirée</h4>
<p>Le 3 février, l'unité COMP C-5 a accusé réception de la demande confirmative et l'a transmise au Secrétariat général, la plaçant ainsi dans le régime du règlement 1049/2001. Ce n'est qu'ensuite qu'est intervenu le rejet pour tardiveté. Nier rétroactivement un écrit déjà reçu et traité se concilie difficilement avec le principe de bonne administration (article 41 de la charte) et avec la protection de la confiance légitime.</p>
<h4>3. Une présomption réfragable qui ne peut être renversée</h4>
<p>Le refus s'appuie sur la présomption générale de confidentialité appliquée aux dossiers de concentration (Odile Jacob, C-404/10 P ; Agrofert, C-477/10 P). Selon cette jurisprudence, la présomption est <strong>réfragable</strong>. Il m'est pourtant reproché de ne pas l'avoir renversée, alors que l'on me refuse jusqu'à l'inventaire du dossier. Une présomption ne peut être renversée à l'égard de documents dont la liste est retenue. Ce raisonnement est intrinsèquement contradictoire.</p>
<h4>4. La présomption ne couvre pas tout</h4>
<p>La présomption générale concerne les documents échangés avec les parties notifiantes. Elle ne s'étend pas automatiquement aux analyses de marché internes de la DG Concurrence elle-même ni à la version non caviardée de la décision de la Commission. Ce sont des actes de l'institution, non des écrits des parties, et ils appelaient une appréciation individuelle que la décision ne comporte pas.</p>
<h4>5. L'accès partiel n'a pas été apprécié</h4>
<p>L'article 4, paragraphe 6, du règlement impose que, lorsque l'exception ne vise que des parties du document, les parties restantes soient divulguées. La décision ne montre pas que cela ait été seulement envisagé.</p>
<h4>6. Intérêt public supérieur et la lacune relative au RGPD</h4>
<p>Lorsque des intérêts commerciaux sont invoqués au titre de l'article 4, paragraphe 2, l'accès doit néanmoins être accordé s'il existe un intérêt public supérieur à la divulgation. Aux points 138 à 142 de la décision M.10815, la Commission indique elle-même qu'elle n'a pas examiné le respect du RGPD par les parties. Une lacune reconnue par l'institution ne saurait être couverte par une confidentialité globale.</p>
<p class="closing"><strong>Le nœud n'est pas une technicité</strong>, mais la combinaison d'un comportement contradictoire (points 1 et 2) et d'une motivation individuelle insuffisante (points 3 à 5). Par la lettre du 20 juillet 2026, je me suis réservé une plainte auprès du Médiateur européen et un recours au titre de l'article 263 TFUE. L'article 8, paragraphe 3, du règlement prévoit en outre que l'absence de réponse dans le délai prescrit vaut réponse négative, ce qui ouvre les mêmes voies de recours.</p>"""

ANALYSIS["sv"] = """
<p class="lead">Det handlar inte om att söka ett kryphål. Akten själv innehåller flera sakliga brister som domstolens fasta rättspraxis erkänner som grunder för ogiltigförklaring. De anges nedan, med den starkaste först.</p>
<h4>1. Ansökan lämnades in i tid — och institutionen motsäger sig själv samma dag</h4>
<p>Artikel 7.2 i förordning (EG) nr 1049/2001 knyter femtondagarsfristen till mottagandet av institutionens svar, inte till det datum då svaret författades. Generaldirektoratet för konkurrens avslag är daterat den 7 januari 2026; fristen löpte alltså till slutet av januari. Detta bekräftas även av kommissionens egen skrivelse av den 20 januari 2026, i vilken den skriftligen angav att fristen då ännu inte hade löpt ut.</p>
<p>Jag utformade och lämnade in den bekräftande ansökan den 26 januari 2026 — fristens sista dag — via plattformen AskTheEU. Access Info Europe har skriftligen bekräftat mottagandet av meddelandet, tidsstämplat den dagen, och är berett att intyga detta. Ett tekniskt gränssnittsfel gjorde att plattformen inte omedelbart vidarebefordrade inlagan till institutionen; den 30 januari sände jag den därför direkt.</p>
<p>Avgörande är vad som skedde den 3 februari 2026. Den dagen bekräftade enheten COMP C-5 mottagandet av den bekräftande ansökan och vidarebefordrade den till generalsekretariatet — en formell processhandling som placerade inlagan inom förordning 1049/2001. Samma dag avvisade generalsekretariatet samma inlaga som för sent inkommen. En del av institutionen handlägger alltså ansökan som tillåtlig medan en annan samma dag förklarar den otillåtlig.</p>
<p>Det rör sig inte om en motsägelse åtskild av veckor, som tidsutdräkten skulle kunna förklara. Det är två sinsemellan oförenliga handlingar av samma institution under en och samma dag. Avvisningen tar dessutom inte alls ställning till den dokumenterade inlagan av den 26 januari eller till den skriftliga bekräftelsen från Access Info Europe — den utgår tyst från datumet den 30 januari som om den tidigare ingivningen inte hade funnits.</p>
<h4>2. Ett processuellt godtagande som inte kan återtas</h4>
<p>Den 3 februari bekräftade enheten COMP C-5 mottagandet av den bekräftande ansökan och vidarebefordrade den till generalsekretariatet, och placerade den därmed inom förordning 1049/2001. Först därefter kom avvisningen på grund av försening. Att retroaktivt förneka en inlaga som redan mottagits och handlagts är svårt att förena med principen om god förvaltning (artikel 41 i stadgan) och med skyddet för berättigade förväntningar.</p>
<h4>3. En motbevisbar presumtion som inte kan motbevisas</h4>
<p>Avslaget stöder sig på den allmänna sekretesspresumtionen i koncentrationsärenden (Odile Jacob, C-404/10 P; Agrofert, C-477/10 P). Enligt den rättspraxisen är presumtionen <strong>motbevisbar</strong>. Jag klandras ändå för att inte ha motbevisat den, samtidigt som jag nekas till och med en förteckning över akten. En presumtion kan inte motbevisas i fråga om handlingar vars förteckning hålls inne. Det resonemanget är internt motsägelsefullt.</p>
<h4>4. Presumtionen omfattar inte allt</h4>
<p>Den allmänna presumtionen avser handlingar som utväxlats med de anmälande parterna. Den omfattar inte automatiskt GD Konkurrens egna interna marknadsanalyser eller den omaskerade texten i kommissionens beslut. Det är institutionens rättsakter, inte parternas inlagor, och de krävde en individuell prövning som beslutet inte innehåller.</p>
<h4>5. Delvis tillgång prövades inte</h4>
<p>Artikel 4.6 i förordningen kräver att om undantaget endast omfattar delar av en handling ska de återstående delarna lämnas ut. Beslutet visar inte att detta över huvud taget övervägdes.</p>
<h4>6. Övervägande allmänintresse och luckan kring dataskyddsförordningen</h4>
<p>När affärsintressen åberopas enligt artikel 4.2 ska tillgång ändå beviljas om det finns ett övervägande allmänintresse av utlämnande. I punkterna 138–142 i beslut M.10815 anger kommissionen själv att den inte prövade parternas efterlevnad av dataskyddsförordningen. En lucka som institutionen medger kan inte täckas av generell sekretess.</p>
<p class="closing"><strong>Kärnan är ingen formalitet</strong>, utan kombinationen av motsägelsefullt handlande (punkterna 1 och 2) och otillräcklig individuell motivering (punkterna 3–5). Genom skrivelsen av den 20 juli 2026 förbehöll jag mig ett klagomål till Europeiska ombudsmannen och en talan enligt artikel 263 FEUF. Artikel 8.3 i förordningen föreskriver dessutom att uteblivet svar inom föreskriven frist ska anses som ett avslag, vilket öppnar samma rättsmedel.</p>"""
